name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3


      # Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18


      # Install dependencies for client-a
      - name: Install dependencies (client-a)
        run: |
          cd client-a
          npm ci


      # Build client-a project
      - name: Build project (client-a)
        run: |
          cd client-a
          npm run build


      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Build & Push Node
        run: |
          docker build -t pratik6958/client-a:latest ./client-a
          docker push pratik6958/client-a:latest


      - name: Build & Push FastAPI
        run: |
          docker build -t pratik6958/client-b:latest ./client-b
          docker push pratik6958/client-b:latest
